spring.application.name=kafka-producer

# Server
server.port=8082

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.group-id=hteao-producer-group

# Topic name
kafka.topic.name=hteao-topic
